# Condor submit file

# container with conda environment
container_image = bsbolt.sif

# Executable and arguments
executable = BSBoltAlign.sh
arguments = $(fq)

# List files that need to be transferred to the job
transfer_input_files = $(fq)_1_val_1.fq.gz, $(fq)_2_val_2.fq.gz, REFERENCE_GENOME, BSBolt_ref.tar.gz #compressed indexed reference genome

# Tell Condor to transfer output to our /results directory
should_transfer_files = YES
#transfer_output_files = $(fq).bam
#transfer_output_remaps = "$(fq).bam=WGBS/$(fq).bam"


Requirements = (Target.HasCHTCStaging == true)

+PreferredPelicanCaches = "osdf-uw-cache.svc.osg-htc.org,osdf1.chic.nrp.internet2.edu"
+PelicanReadTimeout = 5000


# Track job info. Want a log file for all jobs together, while you want an output and error log for each job submitted. Easily tracks the whole job with cond>
log = logs/BSBolt.log
output = logs/BSBolt_$(fq).out
error = logs/BSBolt_$(fq).err

# Resources requests
request_cpus = 10
request_memory = 30GB
request_disk = 100GB

# Tell HTCondor to run our jobs
queue fq from BSBolt_samples.txt
