# Condor submit file

# container with conda environment
container_image = bismark.sif

# Executable and arguments
executable = Bismark_Index.sh

# List files that need to be transferred to the job
transfer_input_files = REFERENCE_GENOME
#should_transfer_file = YES

# Tell Condor to transfer output to our /results directory
transfer_output_files = Bisulfite_Genome
#transfer_output_remaps = "$(fq).fna=WGBS/$(fq).fna"

#transfer_output_remaps = "mapped_$(read_subset_file)_reads_to_genome.sam = ./data/mappedSAM/mapped_$(read_subset_file)_reads_to_genome.sam; "

# Track job info. Want a log file for all jobs together, while you want an output and error log for each job submitted. 
log = logs/BismarkIndex.log
output = logs/BismarkIndex.out
error = logs/BismarkIndex.err

# Resources requests
request_cpus = 2
request_memory = 20GB
request_disk = 15GB
